const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Food = require('../models/Food');

dotenv.config();

const foods = [
  // ============ VEGETARIAN DISHES ============
  // North Indian
  { name: 'Dal Makhani', nameHindi: 'दाल मखनी', category: 'vegetarian', subCategory: 'North Indian', description: 'Creamy black lentils cooked with butter and cream', nutrition: { calories: 235, protein: 9, carbohydrates: 28, fat: 11, fiber: 6, sugar: 3, sodium: 450 }, tags: ['dal', 'lentils', 'punjabi', 'protein'], healthScore: 72, isPopular: true },
  { name: 'Paneer Butter Masala', nameHindi: 'पनीर बटर मसाला', category: 'vegetarian', subCategory: 'North Indian', description: 'Cottage cheese in rich tomato-butter gravy', nutrition: { calories: 320, protein: 14, carbohydrates: 18, fat: 22, fiber: 2, sugar: 6, sodium: 520 }, tags: ['paneer', 'punjabi', 'creamy', 'protein'], healthScore: 58, isPopular: true },
  { name: 'Palak Paneer', nameHindi: 'पालक पनीर', category: 'vegetarian', subCategory: 'North Indian', description: 'Cottage cheese in spinach gravy', nutrition: { calories: 265, protein: 15, carbohydrates: 12, fat: 18, fiber: 4, sugar: 3, sodium: 380 }, tags: ['paneer', 'spinach', 'iron', 'protein'], healthScore: 78, isPopular: true },
  { name: 'Chole Bhature', nameHindi: 'छोले भटूरे', category: 'vegetarian', subCategory: 'North Indian', description: 'Spiced chickpeas with fried bread', nutrition: { calories: 450, protein: 14, carbohydrates: 58, fat: 18, fiber: 8, sugar: 4, sodium: 680 }, tags: ['chickpeas', 'protein', 'punjabi'], healthScore: 52, isPopular: true },
  { name: 'Aloo Gobi', nameHindi: 'आलू गोभी', category: 'vegetarian', subCategory: 'North Indian', description: 'Potato and cauliflower stir-fry', nutrition: { calories: 145, protein: 4, carbohydrates: 22, fat: 5, fiber: 4, sugar: 3, sodium: 320 }, tags: ['potato', 'cauliflower', 'dry sabji'], healthScore: 75, isPopular: false },
  { name: 'Malai Kofta', nameHindi: 'मलाई कोफ्ता', category: 'vegetarian', subCategory: 'North Indian', description: 'Fried paneer balls in creamy gravy', nutrition: { calories: 385, protein: 12, carbohydrates: 28, fat: 26, fiber: 3, sugar: 8, sodium: 490 }, tags: ['paneer', 'creamy', 'rich'], healthScore: 48, isPopular: false },
  { name: 'Rajma Chawal', nameHindi: 'राजमा चावल', category: 'vegetarian', subCategory: 'North Indian', description: 'Kidney beans curry with rice', nutrition: { calories: 340, protein: 14, carbohydrates: 58, fat: 6, fiber: 10, sugar: 3, sodium: 520 }, tags: ['kidney beans', 'protein', 'rice'], healthScore: 75, isPopular: true },
  { name: 'Kadai Paneer', nameHindi: 'कढ़ाई पनीर', category: 'vegetarian', subCategory: 'North Indian', description: 'Paneer with bell peppers in spicy gravy', nutrition: { calories: 295, protein: 14, carbohydrates: 15, fat: 20, fiber: 3, sugar: 4, sodium: 420 }, tags: ['paneer', 'bell pepper', 'spicy'], healthScore: 65, isPopular: false },
  { name: 'Shahi Paneer', nameHindi: 'शाही पनीर', category: 'vegetarian', subCategory: 'North Indian', description: 'Rich paneer in cashew-cream gravy', nutrition: { calories: 345, protein: 15, carbohydrates: 16, fat: 25, fiber: 2, sugar: 5, sodium: 450 }, tags: ['paneer', 'creamy', 'mughlai'], healthScore: 55, isPopular: false },
  { name: 'Matar Paneer', nameHindi: 'मटर पनीर', category: 'vegetarian', subCategory: 'North Indian', description: 'Paneer with green peas curry', nutrition: { calories: 275, protein: 14, carbohydrates: 18, fat: 17, fiber: 5, sugar: 4, sodium: 390 }, tags: ['paneer', 'peas', 'protein'], healthScore: 70, isPopular: false },
  { name: 'Baingan Bharta', nameHindi: 'बैंगन भर्ता', category: 'vegetarian', subCategory: 'North Indian', description: 'Smoky mashed eggplant', nutrition: { calories: 120, protein: 3, carbohydrates: 15, fat: 6, fiber: 5, sugar: 4, sodium: 280 }, tags: ['eggplant', 'smoky', 'low calorie'], healthScore: 82, isPopular: false },
  { name: 'Dum Aloo', nameHindi: 'दम आलू', category: 'vegetarian', subCategory: 'North Indian', description: 'Slow-cooked spiced potatoes', nutrition: { calories: 220, protein: 5, carbohydrates: 32, fat: 9, fiber: 4, sugar: 3, sodium: 350 }, tags: ['potato', 'kashmiri'], healthScore: 60, isPopular: false },
  { name: 'Jeera Rice', nameHindi: 'जीरा राइस', category: 'vegetarian', subCategory: 'North Indian', description: 'Cumin-flavored rice', nutrition: { calories: 180, protein: 4, carbohydrates: 38, fat: 2, fiber: 1, sugar: 0, sodium: 150 }, tags: ['rice', 'cumin', 'side dish'], healthScore: 65, isPopular: true },
  { name: 'Vegetable Biryani', nameHindi: 'वेज बिरयानी', category: 'vegetarian', subCategory: 'North Indian', description: 'Fragrant rice with mixed vegetables', nutrition: { calories: 320, protein: 8, carbohydrates: 52, fat: 10, fiber: 4, sugar: 3, sodium: 480 }, tags: ['biryani', 'rice', 'aromatic'], healthScore: 68, isPopular: true },
  { name: 'Pulao', nameHindi: 'पुलाव', category: 'vegetarian', subCategory: 'North Indian', description: 'Mildly spiced vegetable rice', nutrition: { calories: 250, protein: 6, carbohydrates: 45, fat: 6, fiber: 3, sugar: 2, sodium: 380 }, tags: ['rice', 'vegetables', 'mild'], healthScore: 70, isPopular: false },
  
  // South Indian
  { name: 'Masala Dosa', nameHindi: 'मसाला डोसा', category: 'vegetarian', subCategory: 'South Indian', description: 'Crispy crepe with spiced potato filling', nutrition: { calories: 285, protein: 7, carbohydrates: 48, fat: 8, fiber: 3, sugar: 2, sodium: 420 }, tags: ['dosa', 'fermented', 'breakfast'], healthScore: 72, isPopular: true },
  { name: 'Idli', nameHindi: 'इडली', category: 'vegetarian', subCategory: 'South Indian', description: 'Steamed rice cakes (2 pieces)', nutrition: { calories: 120, protein: 4, carbohydrates: 24, fat: 1, fiber: 2, sugar: 0, sodium: 280 }, tags: ['fermented', 'steamed', 'breakfast', 'healthy'], healthScore: 88, isPopular: true },
  { name: 'Vada', nameHindi: 'वड़ा', category: 'vegetarian', subCategory: 'South Indian', description: 'Crispy lentil fritters (2 pieces)', nutrition: { calories: 195, protein: 8, carbohydrates: 22, fat: 9, fiber: 4, sugar: 1, sodium: 350 }, tags: ['fried', 'lentils', 'breakfast'], healthScore: 58, isPopular: true },
  { name: 'Uttapam', nameHindi: 'उत्तपम', category: 'vegetarian', subCategory: 'South Indian', description: 'Thick rice pancake with vegetables', nutrition: { calories: 210, protein: 6, carbohydrates: 35, fat: 5, fiber: 3, sugar: 2, sodium: 380 }, tags: ['fermented', 'pancake', 'vegetables'], healthScore: 75, isPopular: false },
  { name: 'Sambar', nameHindi: 'सांबर', category: 'vegetarian', subCategory: 'South Indian', description: 'Lentil soup with vegetables', nutrition: { calories: 95, protein: 5, carbohydrates: 14, fat: 2, fiber: 4, sugar: 3, sodium: 420 }, tags: ['lentils', 'soup', 'vegetables'], healthScore: 85, isPopular: true },
  { name: 'Rasam', nameHindi: 'रसम', category: 'vegetarian', subCategory: 'South Indian', description: 'Tangy tamarind soup', nutrition: { calories: 45, protein: 2, carbohydrates: 8, fat: 1, fiber: 1, sugar: 2, sodium: 380 }, tags: ['soup', 'digestive', 'tangy'], healthScore: 82, isPopular: false },
  { name: 'Pongal', nameHindi: 'पोंगल', category: 'vegetarian', subCategory: 'South Indian', description: 'Rice and lentil porridge', nutrition: { calories: 225, protein: 7, carbohydrates: 38, fat: 5, fiber: 3, sugar: 1, sodium: 320 }, tags: ['rice', 'lentils', 'breakfast'], healthScore: 78, isPopular: false },
  { name: 'Bisi Bele Bath', nameHindi: 'बिसि बेले बाथ', category: 'vegetarian', subCategory: 'South Indian', description: 'Spicy rice with lentils and vegetables', nutrition: { calories: 295, protein: 9, carbohydrates: 48, fat: 8, fiber: 5, sugar: 3, sodium: 450 }, tags: ['rice', 'lentils', 'karnataka'], healthScore: 75, isPopular: false },
  { name: 'Coconut Chutney', nameHindi: 'नारियल चटनी', category: 'vegetarian', subCategory: 'South Indian', description: 'Fresh coconut dip', nutrition: { calories: 85, protein: 2, carbohydrates: 6, fat: 6, fiber: 2, sugar: 2, sodium: 180 }, tags: ['coconut', 'condiment', 'dip'], healthScore: 70, isPopular: false },
  { name: 'Tomato Rice', nameHindi: 'टमाटर राइस', category: 'vegetarian', subCategory: 'South Indian', description: 'Tangy tomato-flavored rice', nutrition: { calories: 235, protein: 5, carbohydrates: 42, fat: 5, fiber: 2, sugar: 4, sodium: 380 }, tags: ['rice', 'tomato', 'tangy'], healthScore: 68, isPopular: false },
  { name: 'Lemon Rice', nameHindi: 'लेमन राइस', category: 'vegetarian', subCategory: 'South Indian', description: 'Zesty lemon-flavored rice', nutrition: { calories: 220, protein: 5, carbohydrates: 40, fat: 5, fiber: 2, sugar: 1, sodium: 350 }, tags: ['rice', 'lemon', 'tangy'], healthScore: 72, isPopular: false },
  { name: 'Curd Rice', nameHindi: 'दही चावल', category: 'vegetarian', subCategory: 'South Indian', description: 'Cool yogurt rice', nutrition: { calories: 195, protein: 6, carbohydrates: 32, fat: 5, fiber: 1, sugar: 4, sodium: 280 }, tags: ['rice', 'yogurt', 'cooling'], healthScore: 75, isPopular: false },
  
  // Breads
  { name: 'Roti', nameHindi: 'रोटी', category: 'vegetarian', subCategory: 'Breads', description: 'Whole wheat flatbread', nutrition: { calories: 85, protein: 3, carbohydrates: 18, fat: 1, fiber: 2, sugar: 0, sodium: 120 }, tags: ['bread', 'wheat', 'staple'], healthScore: 80, isPopular: true },
  { name: 'Paratha', nameHindi: 'पराठा', category: 'vegetarian', subCategory: 'Breads', description: 'Layered flatbread with ghee', nutrition: { calories: 165, protein: 4, carbohydrates: 22, fat: 7, fiber: 2, sugar: 0, sodium: 180 }, tags: ['bread', 'ghee', 'breakfast'], healthScore: 62, isPopular: true },
  { name: 'Aloo Paratha', nameHindi: 'आलू पराठा', category: 'vegetarian', subCategory: 'Breads', description: 'Potato-stuffed flatbread', nutrition: { calories: 220, protein: 5, carbohydrates: 32, fat: 8, fiber: 3, sugar: 1, sodium: 250 }, tags: ['bread', 'potato', 'stuffed'], healthScore: 60, isPopular: true },
  { name: 'Naan', nameHindi: 'नान', category: 'vegetarian', subCategory: 'Breads', description: 'Leavened bread from tandoor', nutrition: { calories: 195, protein: 6, carbohydrates: 32, fat: 5, fiber: 2, sugar: 2, sodium: 350 }, tags: ['bread', 'tandoor', 'maida'], healthScore: 52, isPopular: true },
  { name: 'Butter Naan', nameHindi: 'बटर नान', category: 'vegetarian', subCategory: 'Breads', description: 'Naan brushed with butter', nutrition: { calories: 245, protein: 6, carbohydrates: 32, fat: 10, fiber: 2, sugar: 2, sodium: 380 }, tags: ['bread', 'butter', 'tandoor'], healthScore: 48, isPopular: true },
  { name: 'Garlic Naan', nameHindi: 'गार्लिक नान', category: 'vegetarian', subCategory: 'Breads', description: 'Naan with garlic topping', nutrition: { calories: 235, protein: 6, carbohydrates: 34, fat: 8, fiber: 2, sugar: 2, sodium: 390 }, tags: ['bread', 'garlic', 'tandoor'], healthScore: 50, isPopular: false },
  { name: 'Kulcha', nameHindi: 'कुलचा', category: 'vegetarian', subCategory: 'Breads', description: 'Soft leavened bread', nutrition: { calories: 180, protein: 5, carbohydrates: 28, fat: 5, fiber: 1, sugar: 2, sodium: 320 }, tags: ['bread', 'tandoor'], healthScore: 55, isPopular: false },
  { name: 'Puri', nameHindi: 'पूरी', category: 'vegetarian', subCategory: 'Breads', description: 'Deep-fried puffed bread', nutrition: { calories: 150, protein: 3, carbohydrates: 18, fat: 7, fiber: 1, sugar: 0, sodium: 180 }, tags: ['bread', 'fried', 'puffed'], healthScore: 45, isPopular: true },
  { name: 'Bhatura', nameHindi: 'भटूरा', category: 'vegetarian', subCategory: 'Breads', description: 'Large fried bread', nutrition: { calories: 280, protein: 6, carbohydrates: 38, fat: 12, fiber: 2, sugar: 1, sodium: 320 }, tags: ['bread', 'fried', 'maida'], healthScore: 38, isPopular: false },
  { name: 'Rumali Roti', nameHindi: 'रूमाली रोटी', category: 'vegetarian', subCategory: 'Breads', description: 'Thin handkerchief-like bread', nutrition: { calories: 95, protein: 3, carbohydrates: 18, fat: 1, fiber: 1, sugar: 0, sodium: 150 }, tags: ['bread', 'thin', 'mughlai'], healthScore: 68, isPopular: false },
  { name: 'Missi Roti', nameHindi: 'मिस्सी रोटी', category: 'vegetarian', subCategory: 'Breads', description: 'Gram flour flatbread', nutrition: { calories: 130, protein: 5, carbohydrates: 20, fat: 3, fiber: 3, sugar: 1, sodium: 200 }, tags: ['bread', 'gram flour', 'protein'], healthScore: 75, isPopular: false },
  { name: 'Thepla', nameHindi: 'थेपला', category: 'vegetarian', subCategory: 'Breads', description: 'Gujarati spiced flatbread', nutrition: { calories: 145, protein: 4, carbohydrates: 22, fat: 5, fiber: 3, sugar: 1, sodium: 220 }, tags: ['bread', 'gujarati', 'fenugreek'], healthScore: 72, isPopular: false },
  
  // Snacks
  { name: 'Samosa', nameHindi: 'समोसा', category: 'vegetarian', subCategory: 'Snacks', description: 'Fried pastry with potato filling', nutrition: { calories: 245, protein: 5, carbohydrates: 28, fat: 13, fiber: 3, sugar: 2, sodium: 380 }, tags: ['fried', 'snack', 'potato'], healthScore: 42, isPopular: true },
  { name: 'Pakora', nameHindi: 'पकोड़ा', category: 'vegetarian', subCategory: 'Snacks', description: 'Vegetable fritters (5 pieces)', nutrition: { calories: 210, protein: 5, carbohydrates: 22, fat: 12, fiber: 3, sugar: 2, sodium: 350 }, tags: ['fried', 'snack', 'monsoon'], healthScore: 40, isPopular: true },
  { name: 'Pani Puri', nameHindi: 'पानी पूरी', category: 'vegetarian', subCategory: 'Snacks', description: 'Hollow crispy balls with spiced water (6 pieces)', nutrition: { calories: 180, protein: 4, carbohydrates: 32, fat: 4, fiber: 2, sugar: 4, sodium: 520 }, tags: ['chaat', 'street food', 'tangy'], healthScore: 48, isPopular: true },
  { name: 'Bhel Puri', nameHindi: 'भेल पूरी', category: 'vegetarian', subCategory: 'Snacks', description: 'Puffed rice snack mix', nutrition: { calories: 195, protein: 5, carbohydrates: 35, fat: 4, fiber: 3, sugar: 5, sodium: 480 }, tags: ['chaat', 'street food', 'crunchy'], healthScore: 55, isPopular: true },
  { name: 'Sev Puri', nameHindi: 'सेव पूरी', category: 'vegetarian', subCategory: 'Snacks', description: 'Crispy wafers with toppings (6 pieces)', nutrition: { calories: 220, protein: 4, carbohydrates: 30, fat: 9, fiber: 2, sugar: 4, sodium: 450 }, tags: ['chaat', 'street food'], healthScore: 45, isPopular: false },
  { name: 'Dahi Puri', nameHindi: 'दही पूरी', category: 'vegetarian', subCategory: 'Snacks', description: 'Crispy puris with yogurt (6 pieces)', nutrition: { calories: 235, protein: 6, carbohydrates: 32, fat: 8, fiber: 2, sugar: 6, sodium: 420 }, tags: ['chaat', 'yogurt', 'sweet'], healthScore: 52, isPopular: false },
  { name: 'Aloo Tikki', nameHindi: 'आलू टिक्की', category: 'vegetarian', subCategory: 'Snacks', description: 'Spiced potato patties (2 pieces)', nutrition: { calories: 190, protein: 4, carbohydrates: 28, fat: 7, fiber: 3, sugar: 2, sodium: 380 }, tags: ['potato', 'street food', 'crispy'], healthScore: 50, isPopular: true },
  { name: 'Kachori', nameHindi: 'कचोरी', category: 'vegetarian', subCategory: 'Snacks', description: 'Fried pastry with spiced filling', nutrition: { calories: 265, protein: 6, carbohydrates: 30, fat: 14, fiber: 4, sugar: 2, sodium: 420 }, tags: ['fried', 'spicy', 'breakfast'], healthScore: 38, isPopular: false },
  { name: 'Dhokla', nameHindi: 'ढोकला', category: 'vegetarian', subCategory: 'Snacks', description: 'Steamed gram flour cake', nutrition: { calories: 135, protein: 6, carbohydrates: 20, fat: 3, fiber: 2, sugar: 3, sodium: 350 }, tags: ['steamed', 'gujarati', 'healthy'], healthScore: 78, isPopular: true },
  { name: 'Khandvi', nameHindi: 'खांडवी', category: 'vegetarian', subCategory: 'Snacks', description: 'Rolled gram flour strips', nutrition: { calories: 125, protein: 5, carbohydrates: 18, fat: 4, fiber: 2, sugar: 2, sodium: 280 }, tags: ['gujarati', 'light'], healthScore: 75, isPopular: false },
  { name: 'Poha', nameHindi: 'पोहा', category: 'vegetarian', subCategory: 'Snacks', description: 'Flattened rice with peanuts', nutrition: { calories: 185, protein: 5, carbohydrates: 32, fat: 5, fiber: 2, sugar: 2, sodium: 320 }, tags: ['breakfast', 'rice flakes', 'maharashtrian'], healthScore: 72, isPopular: true },
  { name: 'Upma', nameHindi: 'उपमा', category: 'vegetarian', subCategory: 'Snacks', description: 'Semolina porridge with vegetables', nutrition: { calories: 175, protein: 5, carbohydrates: 28, fat: 5, fiber: 3, sugar: 2, sodium: 380 }, tags: ['breakfast', 'semolina', 'south indian'], healthScore: 70, isPopular: true },
  { name: 'Medu Vada', nameHindi: 'मेदु वड़ा', category: 'vegetarian', subCategory: 'Snacks', description: 'Savory lentil doughnut (2 pieces)', nutrition: { calories: 210, protein: 8, carbohydrates: 24, fat: 10, fiber: 4, sugar: 1, sodium: 380 }, tags: ['fried', 'lentils', 'south indian'], healthScore: 55, isPopular: false },

  // ============ NON-VEGETARIAN DISHES ============
  { name: 'Butter Chicken', nameHindi: 'बटर चिकन', category: 'non-vegetarian', subCategory: 'North Indian', description: 'Chicken in creamy tomato-butter gravy', nutrition: { calories: 385, protein: 28, carbohydrates: 12, fat: 26, fiber: 2, sugar: 5, sodium: 580, cholesterol: 95 }, tags: ['chicken', 'creamy', 'punjabi'], healthScore: 55, isPopular: true },
  { name: 'Chicken Tikka Masala', nameHindi: 'चिकन टिक्का मसाला', category: 'non-vegetarian', subCategory: 'North Indian', description: 'Grilled chicken in spiced curry', nutrition: { calories: 345, protein: 32, carbohydrates: 14, fat: 18, fiber: 3, sugar: 4, sodium: 520, cholesterol: 85 }, tags: ['chicken', 'grilled', 'spicy'], healthScore: 62, isPopular: true },
  { name: 'Tandoori Chicken', nameHindi: 'तंदूरी चिकन', category: 'non-vegetarian', subCategory: 'North Indian', description: 'Yogurt-marinated grilled chicken', nutrition: { calories: 265, protein: 35, carbohydrates: 5, fat: 12, fiber: 1, sugar: 2, sodium: 450, cholesterol: 110 }, tags: ['chicken', 'grilled', 'tandoor', 'protein'], healthScore: 75, isPopular: true },
  { name: 'Chicken Biryani', nameHindi: 'चिकन बिरयानी', category: 'non-vegetarian', subCategory: 'Mughlai', description: 'Aromatic rice with spiced chicken', nutrition: { calories: 420, protein: 24, carbohydrates: 48, fat: 16, fiber: 2, sugar: 3, sodium: 620, cholesterol: 75 }, tags: ['biryani', 'rice', 'aromatic', 'chicken'], healthScore: 60, isPopular: true },
  { name: 'Mutton Biryani', nameHindi: 'मटन बिरयानी', category: 'non-vegetarian', subCategory: 'Mughlai', description: 'Aromatic rice with spiced mutton', nutrition: { calories: 465, protein: 26, carbohydrates: 48, fat: 20, fiber: 2, sugar: 3, sodium: 650, cholesterol: 85 }, tags: ['biryani', 'rice', 'mutton'], healthScore: 55, isPopular: true },
  { name: 'Hyderabadi Biryani', nameHindi: 'हैदराबादी बिरयानी', category: 'non-vegetarian', subCategory: 'Mughlai', description: 'Famous dum-style biryani', nutrition: { calories: 445, protein: 25, carbohydrates: 50, fat: 18, fiber: 2, sugar: 3, sodium: 640, cholesterol: 80 }, tags: ['biryani', 'hyderabad', 'dum'], healthScore: 58, isPopular: true },
  { name: 'Rogan Josh', nameHindi: 'रोगन जोश', category: 'non-vegetarian', subCategory: 'North Indian', description: 'Kashmiri mutton curry', nutrition: { calories: 320, protein: 28, carbohydrates: 8, fat: 20, fiber: 2, sugar: 3, sodium: 480, cholesterol: 90 }, tags: ['mutton', 'kashmiri', 'aromatic'], healthScore: 60, isPopular: false },
  { name: 'Keema', nameHindi: 'कीमा', category: 'non-vegetarian', subCategory: 'North Indian', description: 'Spiced minced meat', nutrition: { calories: 285, protein: 22, carbohydrates: 10, fat: 18, fiber: 2, sugar: 3, sodium: 520, cholesterol: 75 }, tags: ['minced', 'spicy', 'protein'], healthScore: 62, isPopular: false },
  { name: 'Chicken Korma', nameHindi: 'चिकन कोरमा', category: 'non-vegetarian', subCategory: 'Mughlai', description: 'Chicken in creamy cashew gravy', nutrition: { calories: 395, protein: 26, carbohydrates: 14, fat: 28, fiber: 2, sugar: 4, sodium: 490, cholesterol: 85 }, tags: ['chicken', 'creamy', 'mild'], healthScore: 52, isPopular: false },
  { name: 'Seekh Kebab', nameHindi: 'सीख कबाब', category: 'non-vegetarian', subCategory: 'Kebabs', description: 'Grilled minced meat skewers (4 pieces)', nutrition: { calories: 245, protein: 22, carbohydrates: 6, fat: 15, fiber: 1, sugar: 1, sodium: 420, cholesterol: 70 }, tags: ['kebab', 'grilled', 'protein'], healthScore: 68, isPopular: true },
  { name: 'Chicken Malai Tikka', nameHindi: 'चिकन मलाई टिक्का', category: 'non-vegetarian', subCategory: 'Kebabs', description: 'Creamy grilled chicken pieces', nutrition: { calories: 275, protein: 28, carbohydrates: 5, fat: 16, fiber: 1, sugar: 2, sodium: 380, cholesterol: 80 }, tags: ['chicken', 'grilled', 'creamy'], healthScore: 70, isPopular: false },
  { name: 'Fish Curry', nameHindi: 'फिश करी', category: 'non-vegetarian', subCategory: 'Coastal', description: 'Spiced fish in coconut gravy', nutrition: { calories: 245, protein: 24, carbohydrates: 8, fat: 14, fiber: 2, sugar: 2, sodium: 450 }, tags: ['fish', 'coastal', 'omega-3'], healthScore: 78, isPopular: false },
  { name: 'Prawn Masala', nameHindi: 'प्रॉन मसाला', category: 'non-vegetarian', subCategory: 'Coastal', description: 'Spiced prawns in tomato gravy', nutrition: { calories: 225, protein: 22, carbohydrates: 10, fat: 12, fiber: 2, sugar: 3, sodium: 520, cholesterol: 150 }, tags: ['prawns', 'seafood', 'protein'], healthScore: 72, isPopular: false },
  { name: 'Egg Curry', nameHindi: 'अंडा करी', category: 'non-vegetarian', subCategory: 'North Indian', description: 'Boiled eggs in spiced gravy', nutrition: { calories: 215, protein: 14, carbohydrates: 10, fat: 14, fiber: 2, sugar: 3, sodium: 420, cholesterol: 185 }, tags: ['egg', 'protein', 'budget'], healthScore: 68, isPopular: true },
  { name: 'Egg Bhurji', nameHindi: 'अंडा भुर्जी', category: 'non-vegetarian', subCategory: 'North Indian', description: 'Spiced scrambled eggs', nutrition: { calories: 195, protein: 14, carbohydrates: 6, fat: 14, fiber: 1, sugar: 2, sodium: 380, cholesterol: 185 }, tags: ['egg', 'breakfast', 'quick'], healthScore: 70, isPopular: true },
  { name: 'Chicken 65', nameHindi: 'चिकन 65', category: 'non-vegetarian', subCategory: 'South Indian', description: 'Spicy fried chicken', nutrition: { calories: 320, protein: 24, carbohydrates: 18, fat: 18, fiber: 1, sugar: 2, sodium: 580, cholesterol: 75 }, tags: ['chicken', 'fried', 'spicy'], healthScore: 48, isPopular: true },
  { name: 'Chicken Chettinad', nameHindi: 'चिकन चेट्टिनाड', category: 'non-vegetarian', subCategory: 'South Indian', description: 'Spicy Tamil Nadu chicken curry', nutrition: { calories: 295, protein: 28, carbohydrates: 10, fat: 16, fiber: 3, sugar: 2, sodium: 480, cholesterol: 80 }, tags: ['chicken', 'spicy', 'tamil'], healthScore: 65, isPopular: false },
  { name: 'Mutton Keema', nameHindi: 'मटन कीमा', category: 'non-vegetarian', subCategory: 'North Indian', description: 'Minced mutton with spices', nutrition: { calories: 310, protein: 24, carbohydrates: 8, fat: 22, fiber: 2, sugar: 2, sodium: 520, cholesterol: 85 }, tags: ['mutton', 'minced', 'protein'], healthScore: 58, isPopular: false },
  { name: 'Chicken Saagwala', nameHindi: 'चिकन साग वाला', category: 'non-vegetarian', subCategory: 'North Indian', description: 'Chicken with spinach', nutrition: { calories: 275, protein: 28, carbohydrates: 8, fat: 15, fiber: 4, sugar: 2, sodium: 420, cholesterol: 75 }, tags: ['chicken', 'spinach', 'iron'], healthScore: 72, isPopular: false },
  { name: 'Mutton Nihari', nameHindi: 'मटन निहारी', category: 'non-vegetarian', subCategory: 'Mughlai', description: 'Slow-cooked mutton stew', nutrition: { calories: 385, protein: 28, carbohydrates: 12, fat: 26, fiber: 2, sugar: 2, sodium: 580, cholesterol: 95 }, tags: ['mutton', 'slow-cooked', 'rich'], healthScore: 52, isPopular: false },

  // ============ JUICES & BEVERAGES ============
  { name: 'Fresh Orange Juice', nameHindi: 'संतरे का जूस', category: 'juices', subCategory: 'Fresh Juice', description: 'Freshly squeezed orange juice (200ml)', nutrition: { calories: 90, protein: 1, carbohydrates: 21, fat: 0, fiber: 0, sugar: 18, sodium: 5, vitaminC: 70 }, tags: ['fresh', 'vitamin c', 'citrus'], healthScore: 75, isPopular: true },
  { name: 'Mango Juice', nameHindi: 'आम का जूस', category: 'juices', subCategory: 'Fresh Juice', description: 'Fresh mango juice (200ml)', nutrition: { calories: 120, protein: 1, carbohydrates: 28, fat: 0, fiber: 1, sugar: 24, sodium: 5, vitaminA: 25, vitaminC: 35 }, tags: ['mango', 'summer', 'sweet'], healthScore: 68, isPopular: true },
  { name: 'Apple Juice', nameHindi: 'सेब का जूस', category: 'juices', subCategory: 'Fresh Juice', description: 'Fresh apple juice (200ml)', nutrition: { calories: 95, protein: 0, carbohydrates: 24, fat: 0, fiber: 0, sugar: 22, sodium: 5 }, tags: ['apple', 'fresh', 'healthy'], healthScore: 70, isPopular: true },
  { name: 'Watermelon Juice', nameHindi: 'तरबूज का जूस', category: 'juices', subCategory: 'Fresh Juice', description: 'Fresh watermelon juice (200ml)', nutrition: { calories: 60, protein: 1, carbohydrates: 14, fat: 0, fiber: 0, sugar: 12, sodium: 5, vitaminC: 15 }, tags: ['watermelon', 'summer', 'hydrating'], healthScore: 82, isPopular: true },
  { name: 'Pomegranate Juice', nameHindi: 'अनार का जूस', category: 'juices', subCategory: 'Fresh Juice', description: 'Fresh pomegranate juice (200ml)', nutrition: { calories: 105, protein: 1, carbohydrates: 26, fat: 0, fiber: 0, sugar: 24, sodium: 10, vitaminC: 20, iron: 3 }, tags: ['pomegranate', 'antioxidant', 'iron'], healthScore: 85, isPopular: true },
  { name: 'Sugarcane Juice', nameHindi: 'गन्ने का रस', category: 'juices', subCategory: 'Fresh Juice', description: 'Fresh sugarcane juice (200ml)', nutrition: { calories: 110, protein: 0, carbohydrates: 27, fat: 0, fiber: 0, sugar: 25, sodium: 15, iron: 2 }, tags: ['sugarcane', 'summer', 'energy'], healthScore: 60, isPopular: true },
  { name: 'Coconut Water', nameHindi: 'नारियल पानी', category: 'juices', subCategory: 'Natural', description: 'Fresh coconut water (200ml)', nutrition: { calories: 45, protein: 1, carbohydrates: 9, fat: 0, fiber: 0, sugar: 6, sodium: 50, potassium: 250 }, tags: ['coconut', 'hydrating', 'electrolytes'], healthScore: 92, isPopular: true },
  { name: 'Lassi (Sweet)', nameHindi: 'मीठी लस्सी', category: 'juices', subCategory: 'Dairy Drinks', description: 'Sweet yogurt drink (200ml)', nutrition: { calories: 165, protein: 5, carbohydrates: 28, fat: 4, fiber: 0, sugar: 24, sodium: 80, calcium: 150 }, tags: ['yogurt', 'punjabi', 'probiotic'], healthScore: 65, isPopular: true },
  { name: 'Lassi (Salted)', nameHindi: 'नमकीन लस्सी', category: 'juices', subCategory: 'Dairy Drinks', description: 'Salted yogurt drink (200ml)', nutrition: { calories: 85, protein: 5, carbohydrates: 8, fat: 4, fiber: 0, sugar: 6, sodium: 280, calcium: 150 }, tags: ['yogurt', 'punjabi', 'probiotic'], healthScore: 78, isPopular: false },
  { name: 'Mango Lassi', nameHindi: 'आम लस्सी', category: 'juices', subCategory: 'Dairy Drinks', description: 'Mango yogurt smoothie (200ml)', nutrition: { calories: 185, protein: 5, carbohydrates: 32, fat: 4, fiber: 1, sugar: 28, sodium: 80, calcium: 150 }, tags: ['mango', 'yogurt', 'creamy'], healthScore: 62, isPopular: true },
  { name: 'Chaas/Buttermilk', nameHindi: 'छाछ', category: 'juices', subCategory: 'Dairy Drinks', description: 'Spiced buttermilk (200ml)', nutrition: { calories: 45, protein: 3, carbohydrates: 5, fat: 2, fiber: 0, sugar: 4, sodium: 250, calcium: 100 }, tags: ['buttermilk', 'digestive', 'probiotic'], healthScore: 88, isPopular: true },
  { name: 'Nimbu Pani', nameHindi: 'नींबू पानी', category: 'juices', subCategory: 'Lemonades', description: 'Lemon water with sugar/salt (200ml)', nutrition: { calories: 45, protein: 0, carbohydrates: 12, fat: 0, fiber: 0, sugar: 10, sodium: 150, vitaminC: 25 }, tags: ['lemon', 'refreshing', 'summer'], healthScore: 80, isPopular: true },
  { name: 'Aam Panna', nameHindi: 'आम पन्ना', category: 'juices', subCategory: 'Traditional', description: 'Raw mango drink (200ml)', nutrition: { calories: 55, protein: 0, carbohydrates: 14, fat: 0, fiber: 0, sugar: 12, sodium: 180, vitaminC: 30 }, tags: ['raw mango', 'summer', 'cooling'], healthScore: 82, isPopular: false },
  { name: 'Jaljeera', nameHindi: 'जलजीरा', category: 'juices', subCategory: 'Traditional', description: 'Cumin-mint drink (200ml)', nutrition: { calories: 35, protein: 1, carbohydrates: 8, fat: 0, fiber: 0, sugar: 6, sodium: 320 }, tags: ['cumin', 'mint', 'digestive'], healthScore: 85, isPopular: false },
  { name: 'Masala Chai', nameHindi: 'मसाला चाय', category: 'beverages', subCategory: 'Hot Drinks', description: 'Spiced Indian tea (150ml)', nutrition: { calories: 75, protein: 2, carbohydrates: 12, fat: 2, fiber: 0, sugar: 10, sodium: 30, calcium: 50 }, tags: ['tea', 'spiced', 'indian'], healthScore: 65, isPopular: true },
  { name: 'Black Coffee', nameHindi: 'ब्लैक कॉफी', category: 'beverages', subCategory: 'Hot Drinks', description: 'Plain black coffee (150ml)', nutrition: { calories: 5, protein: 0, carbohydrates: 1, fat: 0, fiber: 0, sugar: 0, sodium: 5 }, tags: ['coffee', 'caffeine', 'zero calorie'], healthScore: 75, isPopular: true },
  { name: 'Filter Coffee', nameHindi: 'फिल्टर कॉफी', category: 'beverages', subCategory: 'Hot Drinks', description: 'South Indian filter coffee (150ml)', nutrition: { calories: 85, protein: 2, carbohydrates: 10, fat: 4, fiber: 0, sugar: 8, sodium: 35, calcium: 60 }, tags: ['coffee', 'south indian', 'milk'], healthScore: 60, isPopular: true },
  { name: 'Green Tea', nameHindi: 'ग्रीन टी', category: 'beverages', subCategory: 'Hot Drinks', description: 'Antioxidant-rich tea (150ml)', nutrition: { calories: 2, protein: 0, carbohydrates: 0, fat: 0, fiber: 0, sugar: 0, sodium: 0 }, tags: ['tea', 'antioxidant', 'healthy'], healthScore: 95, isPopular: true },
  { name: 'Thandai', nameHindi: 'ठंडाई', category: 'beverages', subCategory: 'Traditional', description: 'Spiced milk drink (200ml)', nutrition: { calories: 195, protein: 6, carbohydrates: 28, fat: 7, fiber: 1, sugar: 22, sodium: 80, calcium: 180 }, tags: ['milk', 'nuts', 'holi'], healthScore: 58, isPopular: false },
  { name: 'Badam Milk', nameHindi: 'बादाम दूध', category: 'beverages', subCategory: 'Dairy Drinks', description: 'Almond-flavored milk (200ml)', nutrition: { calories: 175, protein: 6, carbohydrates: 22, fat: 7, fiber: 1, sugar: 18, sodium: 70, calcium: 180, vitaminE: 8 }, tags: ['almond', 'milk', 'nutritious'], healthScore: 72, isPopular: false },
  { name: 'Rooh Afza', nameHindi: 'रूह अफ़ज़ा', category: 'beverages', subCategory: 'Syrups', description: 'Rose-flavored drink (200ml)', nutrition: { calories: 95, protein: 0, carbohydrates: 24, fat: 0, fiber: 0, sugar: 22, sodium: 15 }, tags: ['rose', 'sweet', 'summer'], healthScore: 45, isPopular: false },

  // ============ PACKED FOODS ============
  { name: 'Maggi Noodles', nameHindi: 'मैगी', category: 'packed-foods', subCategory: 'Instant Noodles', brand: 'Nestle', description: 'Instant noodles (1 pack)', nutrition: { calories: 380, protein: 9, carbohydrates: 52, fat: 15, fiber: 3, sugar: 2, sodium: 950 }, tags: ['instant', 'noodles', 'quick'], healthScore: 32, isPopular: true },
  { name: 'Kurkure', nameHindi: 'कुरकुरे', category: 'packed-foods', subCategory: 'Chips', brand: 'PepsiCo', description: 'Crunchy corn snack (50g)', nutrition: { calories: 270, protein: 4, carbohydrates: 30, fat: 15, fiber: 2, sugar: 3, sodium: 480 }, tags: ['snack', 'crunchy', 'spicy'], healthScore: 28, isPopular: true },
  { name: 'Lays Classic', nameHindi: 'लेज़ क्लासिक', category: 'packed-foods', subCategory: 'Chips', brand: 'PepsiCo', description: 'Potato chips (50g)', nutrition: { calories: 265, protein: 3, carbohydrates: 26, fat: 17, fiber: 2, sugar: 1, sodium: 340 }, tags: ['chips', 'potato', 'salty'], healthScore: 25, isPopular: true },
  { name: 'Parle-G', nameHindi: 'पारले-जी', category: 'packed-foods', subCategory: 'Biscuits', brand: 'Parle', description: 'Glucose biscuits (100g)', nutrition: { calories: 460, protein: 6, carbohydrates: 76, fat: 14, fiber: 2, sugar: 26, sodium: 280 }, tags: ['biscuit', 'glucose', 'tea-time'], healthScore: 38, isPopular: true },
  { name: 'Britannia Good Day', nameHindi: 'गुड डे', category: 'packed-foods', subCategory: 'Biscuits', brand: 'Britannia', description: 'Butter cookies (100g)', nutrition: { calories: 490, protein: 6, carbohydrates: 66, fat: 22, fiber: 2, sugar: 24, sodium: 320 }, tags: ['biscuit', 'butter', 'sweet'], healthScore: 32, isPopular: true },
  { name: 'Haldirams Bhujia', nameHindi: 'हल्दीराम भुजिया', category: 'packed-foods', subCategory: 'Namkeen', brand: 'Haldirams', description: 'Gram flour snack (100g)', nutrition: { calories: 545, protein: 15, carbohydrates: 48, fat: 32, fiber: 8, sugar: 4, sodium: 850 }, tags: ['namkeen', 'crispy', 'spicy'], healthScore: 35, isPopular: true },
  { name: 'Haldirams Aloo Bhujia', nameHindi: 'आलू भुजिया', category: 'packed-foods', subCategory: 'Namkeen', brand: 'Haldirams', description: 'Potato snack (100g)', nutrition: { calories: 520, protein: 10, carbohydrates: 52, fat: 30, fiber: 5, sugar: 3, sodium: 780 }, tags: ['namkeen', 'potato', 'crispy'], healthScore: 32, isPopular: false },
  { name: 'MTR Ready-to-Eat Dal Makhani', nameHindi: 'एमटीआर दाल मखनी', category: 'packed-foods', subCategory: 'Ready to Eat', brand: 'MTR', description: 'Ready-to-eat dal (300g pack)', nutrition: { calories: 285, protein: 12, carbohydrates: 32, fat: 12, fiber: 8, sugar: 4, sodium: 680 }, tags: ['ready-to-eat', 'dal', 'convenient'], healthScore: 55, isPopular: false },
  { name: 'Amul Butter', nameHindi: 'अमूल बटर', category: 'packed-foods', subCategory: 'Dairy', brand: 'Amul', description: 'Salted butter (100g)', nutrition: { calories: 720, protein: 1, carbohydrates: 0, fat: 80, fiber: 0, sugar: 0, sodium: 650, cholesterol: 220 }, tags: ['butter', 'dairy', 'fat'], healthScore: 30, isPopular: true },
  { name: 'Amul Cheese Slice', nameHindi: 'अमूल चीज़', category: 'packed-foods', subCategory: 'Dairy', brand: 'Amul', description: 'Processed cheese (1 slice, 20g)', nutrition: { calories: 65, protein: 3, carbohydrates: 1, fat: 5, fiber: 0, sugar: 0, sodium: 180, calcium: 80, cholesterol: 15 }, tags: ['cheese', 'dairy', 'calcium'], healthScore: 45, isPopular: true },
  { name: 'Tropicana Orange Juice', nameHindi: 'ट्रॉपिकाना', category: 'packed-foods', subCategory: 'Packaged Juices', brand: 'PepsiCo', description: 'Packaged orange juice (200ml)', nutrition: { calories: 88, protein: 1, carbohydrates: 21, fat: 0, fiber: 0, sugar: 18, sodium: 5, vitaminC: 60 }, tags: ['juice', 'orange', 'vitamin c'], healthScore: 55, isPopular: true },
  { name: 'Real Mango Juice', nameHindi: 'रियल मैंगो', category: 'packed-foods', subCategory: 'Packaged Juices', brand: 'Dabur', description: 'Packaged mango juice (200ml)', nutrition: { calories: 115, protein: 0, carbohydrates: 28, fat: 0, fiber: 0, sugar: 26, sodium: 10 }, tags: ['juice', 'mango', 'sweet'], healthScore: 48, isPopular: true },
  { name: 'Coca-Cola', nameHindi: 'कोका कोला', category: 'packed-foods', subCategory: 'Soft Drinks', brand: 'Coca-Cola', description: 'Carbonated soft drink (300ml)', nutrition: { calories: 130, protein: 0, carbohydrates: 34, fat: 0, fiber: 0, sugar: 34, sodium: 30 }, tags: ['soda', 'carbonated', 'sweet'], healthScore: 15, isPopular: true },
  { name: 'Thums Up', nameHindi: 'थम्स अप', category: 'packed-foods', subCategory: 'Soft Drinks', brand: 'Coca-Cola', description: 'Carbonated cola drink (300ml)', nutrition: { calories: 135, protein: 0, carbohydrates: 35, fat: 0, fiber: 0, sugar: 35, sodium: 35 }, tags: ['soda', 'cola', 'indian'], healthScore: 15, isPopular: true },
  { name: 'Sprite', nameHindi: 'स्प्राइट', category: 'packed-foods', subCategory: 'Soft Drinks', brand: 'Coca-Cola', description: 'Lemon-lime soda (300ml)', nutrition: { calories: 125, protein: 0, carbohydrates: 32, fat: 0, fiber: 0, sugar: 32, sodium: 25 }, tags: ['soda', 'lemon', 'lime'], healthScore: 18, isPopular: true },
  { name: 'Red Bull', nameHindi: 'रेड बुल', category: 'packed-foods', subCategory: 'Energy Drinks', brand: 'Red Bull', description: 'Energy drink (250ml)', nutrition: { calories: 110, protein: 0, carbohydrates: 27, fat: 0, fiber: 0, sugar: 27, sodium: 100 }, tags: ['energy', 'caffeine', 'taurine'], healthScore: 20, isPopular: false },
  { name: 'Horlicks', nameHindi: 'हॉर्लिक्स', category: 'packed-foods', subCategory: 'Health Drinks', brand: 'GSK', description: 'Malted health drink (30g in milk)', nutrition: { calories: 180, protein: 8, carbohydrates: 28, fat: 4, fiber: 1, sugar: 18, sodium: 120, calcium: 250, vitaminD: 15 }, tags: ['malt', 'health drink', 'kids'], healthScore: 55, isPopular: true },
  { name: 'Bournvita', nameHindi: 'बॉर्नविटा', category: 'packed-foods', subCategory: 'Health Drinks', brand: 'Cadbury', description: 'Chocolate health drink (30g in milk)', nutrition: { calories: 175, protein: 7, carbohydrates: 30, fat: 3, fiber: 1, sugar: 22, sodium: 100, calcium: 200, vitaminD: 12 }, tags: ['chocolate', 'health drink', 'kids'], healthScore: 52, isPopular: true },

  // ============ FRUITS ============
  { name: 'Apple', nameHindi: 'सेब', category: 'fruits', subCategory: 'Common Fruits', description: 'Medium apple (150g)', nutrition: { calories: 78, protein: 0, carbohydrates: 21, fat: 0, fiber: 4, sugar: 16, sodium: 0, potassium: 160, vitaminC: 8 }, tags: ['apple', 'fiber', 'healthy'], healthScore: 88, isPopular: true },
  { name: 'Banana', nameHindi: 'केला', category: 'fruits', subCategory: 'Common Fruits', description: 'Medium banana (120g)', nutrition: { calories: 105, protein: 1, carbohydrates: 27, fat: 0, fiber: 3, sugar: 14, sodium: 0, potassium: 420 }, tags: ['banana', 'potassium', 'energy'], healthScore: 82, isPopular: true },
  { name: 'Mango', nameHindi: 'आम', category: 'fruits', subCategory: 'Tropical Fruits', description: 'Medium mango (200g)', nutrition: { calories: 135, protein: 1, carbohydrates: 35, fat: 0, fiber: 4, sugar: 30, sodium: 0, vitaminA: 25, vitaminC: 45 }, tags: ['mango', 'summer', 'vitamin a'], healthScore: 78, isPopular: true },
  { name: 'Orange', nameHindi: 'संतरा', category: 'fruits', subCategory: 'Citrus Fruits', description: 'Medium orange (150g)', nutrition: { calories: 70, protein: 1, carbohydrates: 18, fat: 0, fiber: 3, sugar: 14, sodium: 0, vitaminC: 85, potassium: 180 }, tags: ['orange', 'vitamin c', 'citrus'], healthScore: 90, isPopular: true },
  { name: 'Grapes', nameHindi: 'अंगूर', category: 'fruits', subCategory: 'Common Fruits', description: 'Green/black grapes (100g)', nutrition: { calories: 69, protein: 1, carbohydrates: 18, fat: 0, fiber: 1, sugar: 16, sodium: 0, potassium: 190 }, tags: ['grapes', 'antioxidant', 'sweet'], healthScore: 80, isPopular: true },
  { name: 'Papaya', nameHindi: 'पपीता', category: 'fruits', subCategory: 'Tropical Fruits', description: 'Papaya cubes (150g)', nutrition: { calories: 60, protein: 1, carbohydrates: 15, fat: 0, fiber: 3, sugar: 11, sodium: 0, vitaminC: 95, vitaminA: 30 }, tags: ['papaya', 'digestive', 'vitamin c'], healthScore: 92, isPopular: true },
  { name: 'Watermelon', nameHindi: 'तरबूज', category: 'fruits', subCategory: 'Melons', description: 'Watermelon cubes (200g)', nutrition: { calories: 60, protein: 1, carbohydrates: 15, fat: 0, fiber: 1, sugar: 12, sodium: 0, vitaminC: 15, vitaminA: 10 }, tags: ['watermelon', 'hydrating', 'summer'], healthScore: 88, isPopular: true },
  { name: 'Pomegranate', nameHindi: 'अनार', category: 'fruits', subCategory: 'Common Fruits', description: 'Pomegranate seeds (100g)', nutrition: { calories: 83, protein: 2, carbohydrates: 19, fat: 1, fiber: 4, sugar: 14, sodium: 0, vitaminC: 18, iron: 3 }, tags: ['pomegranate', 'antioxidant', 'iron'], healthScore: 92, isPopular: true },
  { name: 'Guava', nameHindi: 'अमरूद', category: 'fruits', subCategory: 'Common Fruits', description: 'Medium guava (100g)', nutrition: { calories: 68, protein: 3, carbohydrates: 14, fat: 1, fiber: 5, sugar: 9, sodium: 0, vitaminC: 230 }, tags: ['guava', 'vitamin c', 'fiber'], healthScore: 95, isPopular: true },
  { name: 'Pineapple', nameHindi: 'अनानास', category: 'fruits', subCategory: 'Tropical Fruits', description: 'Pineapple chunks (150g)', nutrition: { calories: 75, protein: 1, carbohydrates: 20, fat: 0, fiber: 2, sugar: 15, sodium: 0, vitaminC: 80 }, tags: ['pineapple', 'tropical', 'bromelain'], healthScore: 82, isPopular: false },
  { name: 'Chikoo/Sapota', nameHindi: 'चीकू', category: 'fruits', subCategory: 'Common Fruits', description: 'Medium chikoo (100g)', nutrition: { calories: 83, protein: 0, carbohydrates: 20, fat: 1, fiber: 5, sugar: 14, sodium: 0, vitaminC: 15, iron: 2 }, tags: ['chikoo', 'sweet', 'fiber'], healthScore: 78, isPopular: false },
  { name: 'Custard Apple', nameHindi: 'सीताफल', category: 'fruits', subCategory: 'Common Fruits', description: 'Medium sitaphal (100g)', nutrition: { calories: 94, protein: 2, carbohydrates: 24, fat: 0, fiber: 4, sugar: 18, sodium: 0, vitaminC: 20 }, tags: ['custard apple', 'creamy', 'sweet'], healthScore: 75, isPopular: false },
  { name: 'Lychee', nameHindi: 'लीची', category: 'fruits', subCategory: 'Common Fruits', description: 'Lychees (100g, about 10 pieces)', nutrition: { calories: 66, protein: 1, carbohydrates: 17, fat: 0, fiber: 1, sugar: 15, sodium: 0, vitaminC: 72 }, tags: ['lychee', 'summer', 'sweet'], healthScore: 78, isPopular: false },
  { name: 'Strawberry', nameHindi: 'स्ट्रॉबेरी', category: 'fruits', subCategory: 'Berries', description: 'Strawberries (100g)', nutrition: { calories: 32, protein: 1, carbohydrates: 8, fat: 0, fiber: 2, sugar: 5, sodium: 0, vitaminC: 98 }, tags: ['strawberry', 'berry', 'antioxidant'], healthScore: 95, isPopular: true },
  { name: 'Kiwi', nameHindi: 'कीवी', category: 'fruits', subCategory: 'Common Fruits', description: 'Medium kiwi (75g)', nutrition: { calories: 46, protein: 1, carbohydrates: 11, fat: 0, fiber: 2, sugar: 7, sodium: 0, vitaminC: 92, vitaminE: 10 }, tags: ['kiwi', 'vitamin c', 'fiber'], healthScore: 92, isPopular: false },

  // ============ DAIRY ============
  { name: 'Milk (Full Cream)', nameHindi: 'दूध', category: 'dairy', subCategory: 'Milk', description: 'Full cream milk (200ml)', nutrition: { calories: 130, protein: 7, carbohydrates: 10, fat: 7, fiber: 0, sugar: 10, sodium: 100, calcium: 250, vitaminD: 2 }, tags: ['milk', 'calcium', 'protein'], healthScore: 72, isPopular: true },
  { name: 'Milk (Toned)', nameHindi: 'टोंड दूध', category: 'dairy', subCategory: 'Milk', description: 'Toned milk (200ml)', nutrition: { calories: 95, protein: 6, carbohydrates: 10, fat: 3, fiber: 0, sugar: 10, sodium: 100, calcium: 240 }, tags: ['milk', 'low fat', 'calcium'], healthScore: 82, isPopular: true },
  { name: 'Curd/Yogurt', nameHindi: 'दही', category: 'dairy', subCategory: 'Fermented', description: 'Plain curd (100g)', nutrition: { calories: 60, protein: 4, carbohydrates: 5, fat: 3, fiber: 0, sugar: 4, sodium: 50, calcium: 120 }, tags: ['curd', 'probiotic', 'digestive'], healthScore: 88, isPopular: true },
  { name: 'Greek Yogurt', nameHindi: 'ग्रीक योगर्ट', category: 'dairy', subCategory: 'Fermented', description: 'Plain Greek yogurt (100g)', nutrition: { calories: 95, protein: 10, carbohydrates: 4, fat: 5, fiber: 0, sugar: 3, sodium: 40, calcium: 110 }, tags: ['greek yogurt', 'protein', 'thick'], healthScore: 90, isPopular: false },
  { name: 'Paneer', nameHindi: 'पनीर', category: 'dairy', subCategory: 'Cheese', description: 'Fresh cottage cheese (100g)', nutrition: { calories: 265, protein: 18, carbohydrates: 3, fat: 20, fiber: 0, sugar: 2, sodium: 20, calcium: 480 }, tags: ['paneer', 'protein', 'vegetarian'], healthScore: 72, isPopular: true },
  { name: 'Low-Fat Paneer', nameHindi: 'लो फैट पनीर', category: 'dairy', subCategory: 'Cheese', description: 'Low-fat cottage cheese (100g)', nutrition: { calories: 185, protein: 20, carbohydrates: 4, fat: 10, fiber: 0, sugar: 2, sodium: 25, calcium: 450 }, tags: ['paneer', 'low fat', 'protein'], healthScore: 82, isPopular: false },
  { name: 'Ghee', nameHindi: 'घी', category: 'dairy', subCategory: 'Fats', description: 'Clarified butter (1 tbsp, 14g)', nutrition: { calories: 125, protein: 0, carbohydrates: 0, fat: 14, fiber: 0, sugar: 0, sodium: 0, vitaminA: 8, vitaminE: 2 }, tags: ['ghee', 'fat', 'traditional'], healthScore: 55, isPopular: true },
  { name: 'Khoya/Mawa', nameHindi: 'खोया', category: 'dairy', subCategory: 'Concentrated', description: 'Reduced milk solid (50g)', nutrition: { calories: 210, protein: 8, carbohydrates: 12, fat: 15, fiber: 0, sugar: 10, sodium: 50, calcium: 200 }, tags: ['khoya', 'sweets', 'concentrated'], healthScore: 45, isPopular: false },
  { name: 'Cream', nameHindi: 'क्रीम', category: 'dairy', subCategory: 'Cream', description: 'Fresh cream (50g)', nutrition: { calories: 170, protein: 1, carbohydrates: 2, fat: 18, fiber: 0, sugar: 1, sodium: 15 }, tags: ['cream', 'fat', 'cooking'], healthScore: 35, isPopular: false },
  { name: 'Cottage Cheese (Low Fat)', nameHindi: 'कॉटेज चीज़', category: 'dairy', subCategory: 'Cheese', description: 'Low-fat cottage cheese (100g)', nutrition: { calories: 98, protein: 11, carbohydrates: 3, fat: 4, fiber: 0, sugar: 3, sodium: 360, calcium: 83 }, tags: ['cottage cheese', 'protein', 'low fat'], healthScore: 80, isPopular: false },

  // ============ GRAINS & CEREALS ============
  { name: 'White Rice (Cooked)', nameHindi: 'चावल', category: 'grains', subCategory: 'Rice', description: 'Cooked white rice (150g)', nutrition: { calories: 195, protein: 4, carbohydrates: 44, fat: 0, fiber: 1, sugar: 0, sodium: 5 }, tags: ['rice', 'carbs', 'staple'], healthScore: 55, isPopular: true },
  { name: 'Brown Rice (Cooked)', nameHindi: 'ब्राउन राइस', category: 'grains', subCategory: 'Rice', description: 'Cooked brown rice (150g)', nutrition: { calories: 165, protein: 4, carbohydrates: 35, fat: 1, fiber: 3, sugar: 0, sodium: 5 }, tags: ['brown rice', 'fiber', 'whole grain'], healthScore: 78, isPopular: false },
  { name: 'Basmati Rice (Cooked)', nameHindi: 'बासमती चावल', category: 'grains', subCategory: 'Rice', description: 'Cooked basmati rice (150g)', nutrition: { calories: 180, protein: 4, carbohydrates: 40, fat: 0, fiber: 1, sugar: 0, sodium: 5 }, tags: ['basmati', 'aromatic', 'premium'], healthScore: 60, isPopular: true },
  { name: 'Wheat Flour', nameHindi: 'गेहूं का आटा', category: 'grains', subCategory: 'Flour', description: 'Whole wheat flour (100g)', nutrition: { calories: 340, protein: 13, carbohydrates: 72, fat: 2, fiber: 11, sugar: 1, sodium: 2, iron: 15 }, tags: ['wheat', 'flour', 'roti'], healthScore: 75, isPopular: true },
  { name: 'Oats', nameHindi: 'ओट्स', category: 'grains', subCategory: 'Cereals', description: 'Rolled oats dry (40g)', nutrition: { calories: 150, protein: 5, carbohydrates: 27, fat: 3, fiber: 4, sugar: 1, sodium: 0, iron: 8 }, tags: ['oats', 'fiber', 'breakfast'], healthScore: 88, isPopular: true },
  { name: 'Quinoa (Cooked)', nameHindi: 'क्विनोआ', category: 'grains', subCategory: 'Supergrains', description: 'Cooked quinoa (150g)', nutrition: { calories: 180, protein: 6, carbohydrates: 32, fat: 3, fiber: 4, sugar: 1, sodium: 10, iron: 12 }, tags: ['quinoa', 'protein', 'superfood'], healthScore: 92, isPopular: false },
  { name: 'Daliya/Broken Wheat', nameHindi: 'दलिया', category: 'grains', subCategory: 'Cereals', description: 'Cooked broken wheat (150g)', nutrition: { calories: 135, protein: 5, carbohydrates: 28, fat: 1, fiber: 5, sugar: 1, sodium: 5 }, tags: ['daliya', 'fiber', 'healthy'], healthScore: 85, isPopular: true },
  { name: 'Semolina/Suji', nameHindi: 'सूजी', category: 'grains', subCategory: 'Flour', description: 'Semolina (100g dry)', nutrition: { calories: 360, protein: 11, carbohydrates: 73, fat: 1, fiber: 4, sugar: 1, sodium: 5, iron: 8 }, tags: ['suji', 'upma', 'halwa'], healthScore: 60, isPopular: true },
  { name: 'Cornflakes', nameHindi: 'कॉर्नफ्लेक्स', category: 'grains', subCategory: 'Breakfast Cereals', description: 'Plain cornflakes (30g)', nutrition: { calories: 115, protein: 2, carbohydrates: 26, fat: 0, fiber: 1, sugar: 3, sodium: 200, iron: 25 }, tags: ['cornflakes', 'breakfast', 'quick'], healthScore: 55, isPopular: true },
  { name: 'Muesli', nameHindi: 'म्यूज़ली', category: 'grains', subCategory: 'Breakfast Cereals', description: 'Mixed muesli (50g)', nutrition: { calories: 180, protein: 5, carbohydrates: 32, fat: 5, fiber: 4, sugar: 12, sodium: 20, iron: 15 }, tags: ['muesli', 'nuts', 'breakfast'], healthScore: 75, isPopular: false },
  { name: 'Popcorn (Plain)', nameHindi: 'पॉपकॉर्न', category: 'grains', subCategory: 'Snacks', description: 'Air-popped popcorn (30g)', nutrition: { calories: 115, protein: 4, carbohydrates: 23, fat: 1, fiber: 4, sugar: 0, sodium: 5 }, tags: ['popcorn', 'low calorie', 'fiber'], healthScore: 72, isPopular: false },
  { name: 'Besan/Gram Flour', nameHindi: 'बेसन', category: 'grains', subCategory: 'Flour', description: 'Gram flour (100g)', nutrition: { calories: 387, protein: 22, carbohydrates: 58, fat: 7, fiber: 10, sugar: 10, sodium: 60, iron: 18 }, tags: ['besan', 'protein', 'pakora'], healthScore: 78, isPopular: true },

  // ============ DESSERTS ============
  { name: 'Gulab Jamun', nameHindi: 'गुलाब जामुन', category: 'desserts', subCategory: 'Indian Sweets', description: 'Fried milk balls in syrup (2 pieces)', nutrition: { calories: 295, protein: 4, carbohydrates: 42, fat: 12, fiber: 0, sugar: 38, sodium: 80 }, tags: ['sweet', 'fried', 'indian'], healthScore: 25, isPopular: true },
  { name: 'Rasgulla', nameHindi: 'रसगुल्ला', category: 'desserts', subCategory: 'Indian Sweets', description: 'Spongy cheese balls in syrup (2 pieces)', nutrition: { calories: 185, protein: 5, carbohydrates: 35, fat: 3, fiber: 0, sugar: 32, sodium: 50 }, tags: ['sweet', 'bengali', 'spongy'], healthScore: 35, isPopular: true },
  { name: 'Kheer', nameHindi: 'खीर', category: 'desserts', subCategory: 'Indian Sweets', description: 'Rice pudding (150g)', nutrition: { calories: 225, protein: 6, carbohydrates: 38, fat: 6, fiber: 0, sugar: 28, sodium: 70, calcium: 150 }, tags: ['kheer', 'rice', 'milk'], healthScore: 40, isPopular: true },
  { name: 'Gajar Halwa', nameHindi: 'गाजर हलवा', category: 'desserts', subCategory: 'Indian Sweets', description: 'Carrot pudding (100g)', nutrition: { calories: 265, protein: 5, carbohydrates: 38, fat: 11, fiber: 2, sugar: 32, sodium: 60, vitaminA: 180 }, tags: ['halwa', 'carrot', 'winter'], healthScore: 38, isPopular: true },
  { name: 'Jalebi', nameHindi: 'जलेबी', category: 'desserts', subCategory: 'Indian Sweets', description: 'Crispy fried sweets (3 pieces)', nutrition: { calories: 310, protein: 3, carbohydrates: 52, fat: 11, fiber: 0, sugar: 42, sodium: 120 }, tags: ['jalebi', 'fried', 'crispy'], healthScore: 20, isPopular: true },
  { name: 'Ladoo (Besan)', nameHindi: 'बेसन लड्डू', category: 'desserts', subCategory: 'Indian Sweets', description: 'Gram flour sweet ball (1 piece)', nutrition: { calories: 195, protein: 4, carbohydrates: 22, fat: 11, fiber: 1, sugar: 16, sodium: 30 }, tags: ['ladoo', 'besan', 'ghee'], healthScore: 35, isPopular: true },
  { name: 'Barfi', nameHindi: 'बर्फी', category: 'desserts', subCategory: 'Indian Sweets', description: 'Milk-based sweet (2 pieces)', nutrition: { calories: 185, protein: 4, carbohydrates: 28, fat: 7, fiber: 0, sugar: 24, sodium: 40, calcium: 80 }, tags: ['barfi', 'milk', 'sweet'], healthScore: 32, isPopular: true },
  { name: 'Rasmalai', nameHindi: 'रसमलाई', category: 'desserts', subCategory: 'Indian Sweets', description: 'Cheese patties in cream (2 pieces)', nutrition: { calories: 245, protein: 7, carbohydrates: 32, fat: 10, fiber: 0, sugar: 28, sodium: 60, calcium: 120 }, tags: ['rasmalai', 'bengali', 'creamy'], healthScore: 38, isPopular: true },
  { name: 'Kulfi', nameHindi: 'कुल्फी', category: 'desserts', subCategory: 'Frozen', description: 'Indian ice cream (1 stick)', nutrition: { calories: 165, protein: 4, carbohydrates: 22, fat: 7, fiber: 0, sugar: 18, sodium: 45, calcium: 100 }, tags: ['kulfi', 'frozen', 'malai'], healthScore: 42, isPopular: true },
  { name: 'Phirni', nameHindi: 'फिरनी', category: 'desserts', subCategory: 'Indian Sweets', description: 'Ground rice pudding (100g)', nutrition: { calories: 185, protein: 4, carbohydrates: 32, fat: 5, fiber: 0, sugar: 24, sodium: 50, calcium: 100 }, tags: ['phirni', 'rice', 'cold'], healthScore: 40, isPopular: false },
  { name: 'Sandesh', nameHindi: 'संदेश', category: 'desserts', subCategory: 'Indian Sweets', description: 'Bengali cheese sweet (2 pieces)', nutrition: { calories: 145, protein: 5, carbohydrates: 22, fat: 4, fiber: 0, sugar: 18, sodium: 30, calcium: 80 }, tags: ['sandesh', 'bengali', 'light'], healthScore: 45, isPopular: false },
  { name: 'Halwa (Suji)', nameHindi: 'सूजी हलवा', category: 'desserts', subCategory: 'Indian Sweets', description: 'Semolina pudding (100g)', nutrition: { calories: 285, protein: 4, carbohydrates: 42, fat: 12, fiber: 1, sugar: 28, sodium: 50 }, tags: ['halwa', 'suji', 'ghee'], healthScore: 30, isPopular: true },
  { name: 'Malpua', nameHindi: 'मालपुआ', category: 'desserts', subCategory: 'Indian Sweets', description: 'Sweet pancakes (2 pieces)', nutrition: { calories: 275, protein: 5, carbohydrates: 38, fat: 12, fiber: 1, sugar: 26, sodium: 80 }, tags: ['malpua', 'pancake', 'fried'], healthScore: 28, isPopular: false },
  { name: 'Chocolate Cake', nameHindi: 'चॉकलेट केक', category: 'desserts', subCategory: 'Cakes', description: 'Chocolate cake slice (80g)', nutrition: { calories: 295, protein: 4, carbohydrates: 38, fat: 15, fiber: 2, sugar: 28, sodium: 220 }, tags: ['cake', 'chocolate', 'western'], healthScore: 22, isPopular: true },
  { name: 'Brownie', nameHindi: 'ब्राउनी', category: 'desserts', subCategory: 'Cakes', description: 'Chocolate brownie (60g)', nutrition: { calories: 260, protein: 3, carbohydrates: 32, fat: 14, fiber: 2, sugar: 24, sodium: 120 }, tags: ['brownie', 'chocolate', 'dense'], healthScore: 25, isPopular: true }
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing foods
    await Food.deleteMany({});
    console.log('🗑️  Cleared existing foods');

    // Insert new foods
    const result = await Food.insertMany(foods);
    console.log(`✅ Inserted ${result.length} food items`);

    // Summary
    const categories = await Food.aggregate([
      { $group: { _id: '$category', count: { $sum: 1 } } },
      { $sort: { count: -1 } }
    ]);
    
    console.log('\n📊 Foods by category:');
    categories.forEach(cat => {
      console.log(`   ${cat._id}: ${cat.count} items`);
    });

    console.log('\n🎉 Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error.message);
    process.exit(1);
  }
};

seedDatabase();
